### ISSUE TITLE
Reloadable save file not working

### ISSUE THREAD

**Issue by CAMSull** [Shadudev/HollowKnight.MultiWorld#37] opened 2023-04-30 12:53 UTC
1. Me and my friend start the server and sessions with item sync working
2. We collect items and it works.
3. We close the server and everything
4. When we reopen the savefiles and connect the itemsync stop working

Are we ment to reconnect manually to the item sync server because it seems like it should automaticallydo that.

**Comment by Shadudev** [comment] 2023-04-30 13:06
Hi, the public server contains a fix for this issue, though I unfortunately didn't upload the bugfix as a new release since it isn't finished.
I'll upload some server files in a few hours and reply again to keep you updated.

**Comment by Shadudev** [comment] 2023-05-02 16:07
Hi, updating again that the issue is in the mod. Currently working on a fix, please be on the lookout for the next release.
You're also welcomed to follow up on the HK discord server on that matter, as I'll be posting there once the fixed version is out

**Closed by Shadudev** 2023-05-02 16:07 UTC
